
package resources;
// Generated 12.Nis.2018 16:06:29 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "Admin", catalog = "kutuphane")
public class Admin implements java.io.Serializable {
	

	private int adminId;
	private String adminAdi;
	private String adminSoyadi;
	private String adminEposta;
	private String adminSifre;
	private String adminAdres;

	public Admin() {
	}

	public Admin(int adminId) {
		this.adminId = adminId;
	}

	public Admin(int adminId, String adminAdi, String adminSoyadi, String adminEposta, String adminSifre,
			String adminAdres) {
		this.adminId = adminId;
		this.adminAdi = adminAdi;
		this.adminSoyadi = adminSoyadi;
		this.adminEposta = adminEposta;
		this.adminSifre = adminSifre;
		this.adminAdres = adminAdres;
	}

	@Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "AdminID", unique = true, nullable = false)
	public int getAdminId() {
		return this.adminId;
	}

	public void setAdminId(int adminId) {
		this.adminId = adminId;
	}

	@Column(name = "Admin_Adi")
	public String getAdminAdi() {
		return this.adminAdi;
	}

	public void setAdminAdi(String adminAdi) {
		this.adminAdi = adminAdi;
	}

	@Column(name = "Admin_Soyadi")
	public String getAdminSoyadi() {
		return this.adminSoyadi;
	}

	public void setAdminSoyadi(String adminSoyadi) {
		this.adminSoyadi = adminSoyadi;
	}

	@Column(name = "Admin_EPosta")
	public String getAdminEposta() {
		return this.adminEposta;
	}

	public void setAdminEposta(String adminEposta) {
		this.adminEposta = adminEposta;
	}

	@Column(name = "Admin_Sifre")
	public String getAdminSifre() {
		return this.adminSifre;
	}

	public void setAdminSifre(String adminSifre) {
		this.adminSifre = adminSifre;
	}

	@Column(name = "Admin_Adres")
	public String getAdminAdres() {
		return this.adminAdres;
	}

	public void setAdminAdres(String adminAdres) {
		this.adminAdres = adminAdres;
	}

}
