package resources;
// Generated 12.Nis.2018 16:06:29 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Kitaplar generated by hbm2java
 */
@Entity
@Table(name = "Kitaplar", catalog = "kutuphane")
public class Kitaplar implements java.io.Serializable {

	private int kitapId;
	private Uyeler uyeler;
	private String kitapAdi;
	private String kitapYazari;
	private Integer kitapSayfaSayisi;
	private Date kitapVerilisTarihi;
	private Date kitapAlisTarihi;
	private Boolean kitapUyedeMi;
	private String kitapYayinEvi;
	private String kitapresmi;

	public Kitaplar() {
	}

	public Kitaplar(int kitapId, Uyeler uyeler, String kitapAdi, Date kitapVerilisTarihi) {
		this.kitapId = kitapId;
		this.uyeler = uyeler;
		this.kitapAdi = kitapAdi;
		this.kitapVerilisTarihi = kitapVerilisTarihi;
	}

	public Kitaplar(int kitapId, Uyeler uyeler, String kitapAdi, String kitapYazari, Integer kitapSayfaSayisi,
			Date kitapVerilisTarihi, Date kitapAlisTarihi, Boolean kitapUyedeMi,String kitapYayinEvi,String kitapresmi) {
		this.kitapId = kitapId;
		this.uyeler = uyeler;
		this.kitapAdi = kitapAdi;
		this.kitapYazari = kitapYazari;
		this.kitapSayfaSayisi = kitapSayfaSayisi;
		this.kitapVerilisTarihi = kitapVerilisTarihi;
		this.kitapAlisTarihi = kitapAlisTarihi;
		this.kitapUyedeMi = kitapUyedeMi;
		this.kitapYayinEvi=kitapYayinEvi;
		this.kitapresmi=kitapresmi;
	}

	@Id

	@Column(name = "Kitap_ID", unique = true, nullable = false)
	public int getKitapId() {
		return this.kitapId;
	}

	public void setKitapId(int kitapId) {
		this.kitapId = kitapId;
	}

	@ManyToOne(fetch = FetchType.EAGER
			)
	@JoinColumn(name = "Uye_TC")
	public Uyeler getUyeler() {
		return this.uyeler;
	}

	public void setUyeler(Uyeler uyeler) {
		this.uyeler = uyeler;
	}

	@Column(name = "Kitap_Adi", nullable = false)
	public String getKitapAdi() {
		return this.kitapAdi;
	}

	public void setKitapAdi(String kitapAdi) {
		this.kitapAdi = kitapAdi;
	}

	@Column(name = "Kitap_Yazari")
	public String getKitapYazari() {
		return this.kitapYazari;
	}

	public void setKitapYazari(String kitapYazari) {
		this.kitapYazari = kitapYazari;
	}

	@Column(name = "Kitap_SayfaSayisi")
	public Integer getKitapSayfaSayisi() {
		return this.kitapSayfaSayisi;
	}

	public void setKitapSayfaSayisi(Integer kitapSayfaSayisi) {
		this.kitapSayfaSayisi = kitapSayfaSayisi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Kitap_Verilis_Tarihi", length = 10)
	public Date getKitapVerilisTarihi() {
		return this.kitapVerilisTarihi;
	}

	public void setKitapVerilisTarihi(Date kitapVerilisTarihi) {
		this.kitapVerilisTarihi = kitapVerilisTarihi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Kitap_Alis_Tarihi", length = 10)
	public Date getKitapAlisTarihi() {
		return this.kitapAlisTarihi;
	}

	public void setKitapAlisTarihi(Date kitapAlisTarihi) {
		this.kitapAlisTarihi = kitapAlisTarihi;
	}

	@Column(name = "Kitap_Uyede_Mi")
	public Boolean getKitapUyedeMi() {
		return this.kitapUyedeMi;
	}

	public void setKitapUyedeMi(Boolean kitapUyedeMi) {
		this.kitapUyedeMi = kitapUyedeMi;
	}
	
	@Column(name = "Kitap_Yayin_Evi")
	public String getKitapYayinEvi() {
		return this.kitapYayinEvi;
	}

	public void setKitapYayinEvi(String kitapYayinEvi) {
		this.kitapYayinEvi = kitapYayinEvi;
	}
	
	@Column(name = "Kitap_Resmi")
	public String getKitapResmi() {
		return this.kitapresmi;
	}

	public void setKitapResmi(String kitapresmi) {
		this.kitapresmi = kitapresmi;
	}

}
