package resources;
// Generated 12.Nis.2018 16:06:29 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Uyeler generated by hbm2java
 */
@Entity
@Table(name = "Uyeler", catalog = "kutuphane")
public class Uyeler implements java.io.Serializable {

	private Long uyeTc;
	private String uyeAdi;
	private String uyeSoyadi;
	private String uyeTelefon;
	private String uyeAdres;
	private Date uyeBaþlangicTarihi;
	private String uyeEMail;
	private Set<Kitaplar> kitaplars = new HashSet<Kitaplar>(0);

	public Uyeler() {
	}

	public Uyeler(Long uyeTc) {
		this.uyeTc = uyeTc;
	}

	public Uyeler(Long uyeTc, String uyeAdi, String uyeSoyadi, String uyeTelefon, String uyeAdres,
			Date uyeBaþlangicTarihi, Set<Kitaplar> kitaplars,String uyeEMail) {
		this.uyeTc = uyeTc;
		this.uyeAdi = uyeAdi;
		this.uyeSoyadi = uyeSoyadi;
		this.uyeTelefon = uyeTelefon;
		this.uyeAdres = uyeAdres;
		this.uyeBaþlangicTarihi = uyeBaþlangicTarihi;
		this.kitaplars = kitaplars;
		this.uyeEMail=uyeEMail;
	}

	@Id

	@Column(name = "Uye_TC", unique = true)
	public Long getUyeTc() {
		return this.uyeTc;
	}

	public void setUyeTc(Long uyeTc) {
		this.uyeTc = uyeTc;
	}

	@Column(name = "Uye_Adi")
	public String getUyeAdi() {
		return this.uyeAdi;
	}

	public void setUyeAdi(String uyeAdi) {
		this.uyeAdi = uyeAdi;
	}
	
	@Column(name = "Uye_EMail")
	public String getUyeEMail() {
		return this.uyeEMail;
	}

	public void setUyeEMail(String uyeEMail) {
		this.uyeEMail = uyeEMail;
	}

	@Column(name = "Uye_Soyadi")
	public String getUyeSoyadi() {
		return this.uyeSoyadi;
	}

	public void setUyeSoyadi(String uyeSoyadi) {
		this.uyeSoyadi = uyeSoyadi;
	}

	@Column(name = "Uye_Telefon")
	public String getUyeTelefon() {
		return this.uyeTelefon;
	}

	public void setUyeTelefon(String uyeTelefon) {
		this.uyeTelefon = uyeTelefon;
	}

	@Column(name = "Uye_Adres")
	public String getUyeAdres() {
		return this.uyeAdres;
	}

	public void setUyeAdres(String uyeAdres) {
		this.uyeAdres = uyeAdres;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Uye_Baþlangic_Tarihi", length = 10)
	public Date getUyeBaþlangicTarihi() {
		return this.uyeBaþlangicTarihi;
	}

	public void setUyeBaþlangicTarihi(Date uyeBaþlangicTarihi) {
		this.uyeBaþlangicTarihi = uyeBaþlangicTarihi;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "uyeler")
	public Set<Kitaplar> getKitaplars() {
		return this.kitaplars;
	}

	public void setKitaplars(Set<Kitaplar> kitaplars) {
		this.kitaplars = kitaplars;
	}

}
